
name = "firewall-wiki-cf"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "firewall_wiki_db"
database_id = "3275c7da-7a63-44d3-886f-9c3b2bc58339"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "firewall-wiki-attachments"
